### ISSUE TITLE
Config file $domain

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library-demo#10]
Adjust config file so that $domain gets dynamically set so people don't have to worry about updating it for their server.

If I like this I should go ahead and apply it to the [class library sample file](https://github.com/angelleye/paypal-php-library/blob/dev/samples/config/config-sample.php) as well.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PCLDK-8
