### ISSUE TITLE
Samples - Website Payments Pro 3.0

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library-demo#11]
DoDirectPayment sample.

**Comment by angelleye** [comment]
This will be the same as the PayFlow basic demo which is already done in #12 but it will use the DoDirectPayment API instead of PayFlow.

**Comment by angelleye** [comment]
We need to add a picture / link from the home page to this kit.  We'll call this one...

Website Payments Pro 3.0
Basic

**Comment by angelleye** [comment]
We need to adjust the demo path/folder name.  Instead of "dodirectpayment-credit-cart-checkout" I'd like it to be "website-payments-pro-30-basic"

**Comment by angelleye** [comment]
I noticed we have MasterCard hard-coded in the DoDirectPament.php code.  This means that the only card numbers that would work are MasterCard numbers.  

Most people will use the sample provided in the note that is displayed, but we need to make sure this functions no matter what card people use.

We need to either add a drop down box option to the checkout form so people can select the type, or what you could do is dynamically set the type based on the first number of the card number.

3 = Amex
4 = Visa
5 = MasterCard
6 = Discover

**Comment by angelleye** [comment]
Please adjust the pricing so it always uses 2 decimal places.  Right now it's only displaying the whole number:

![image](https://cloud.githubusercontent.com/assets/629241/15209301/eeaa59cc-17f5-11e6-98e7-f988461b2276.png)

**Comment by angelleye** [comment]
In DoDirectPayment.php you are correctly checking for both Success and SuccessWithWarning...

`if (isset($PayPalResult['ACK']) && ($PayPalResult['ACK'] == 'Success' || $PayPalResult['ACK'] == 'SuccessWithWarning')) {`

I just want to point out for future reference the class library includes a function called $APICallSuccessful($Ack) that will check both of those for you, as well as another possible value, "PartialSuccess".

```
	function APICallSuccessful($ack)
	{
		if(strtoupper($ack) != 'SUCCESS' && strtoupper($ack) != 'SUCCESSWITHWARNING' && strtoupper($ack) != 'PARTIALSUCCESS')
		{
			return false;
		}
		else
		{
			return true;
		}
	}
```

**Comment by angelleye** [comment]
I forced an API error to test that experience, and I wound up on the error page with empty error values.

Take a look at the /demo/express-checkout-basic/SetExpressCheckout.php file and see how I handled the API result at the end...

```
if($PayPal->APICallSuccessful($PayPalResult['ACK']))
{
    $_SESSION['paypal_token'] = isset($PayPalResult['TOKEN']) ? $PayPalResult['TOKEN'] : '';
    header('Location: ' . $PayPalResult['REDIRECTURL']);
}
else
{
    $_SESSION['paypal_errors'] = $PayPalResult['ERRORS'];
    header('Location: /demo/error.php');
}
```

That is a good example of the use of the APICallSuccessful() function that I mentioned above, as well as pulling the errors straight from $PayPalResult.  It prepares that array and includes it in the result so you don't have to make it like you did.

Please make this adjustment here, and then re-test to ensure everything is working as expected.  The testing should include a forced error from the API.  An easy way to do this is to make one of your API credential values incorrect.

**Comment by angelleye** [comment]
I noticed that you included cart items in the API request for this basic demo.  We actually don't want to do that here.  

Just like with Express Checkout, this will just be the "Basic" demo with nothing but a total amount passed to PayPal.

Then we'll do a "with Line Items" demo that is separate from that, and adds the line items to the request.

So please go ahead and remove the line items from DoDirectPayment.php so they aren't included in the request to PayPal.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PCLDK-9
