### ISSUE TITLE
Samples - PayFlow Basic

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library-demo#12]
Replicate the other demos, but then set it up with a basic PayFlow credit card checkout instead of PayPal.

We'll have to add some basic checkout fields to the demo shopping cart for this.

**Comment by kcppdevelopers** [comment]
I am done with this issue and push to issue #12 for your review.

**Comment by angelleye** [comment]
In #11 I provided the PSD file for the home page images.  We need to add one for this demo.  Use the name...

Payments Pro PayFlow
Basic
