### ISSUE TITLE
Separate Demo Kits

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/paypal-php-library-demo#14]
https://angelleye.atlassian.net/browse/PPCL-3

**Comment by tejasm-itpath** [comment]
@Commits are 

https://github.com/angelleye/paypal-php-library-demo/commit/c5aa796117395a3fb9f6ab7c596f6aed7189a801

and 

https://github.com/angelleye/paypal-php-library-demo/commit/45c8561c6c6a5dcdb0fdc3ccd2212c36928ac383

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PCLDK-10
