### ISSUE TITLE
"Smart Buttons" demo kit and use JSv4 integration

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/paypal-php-library-demo#15]
As per Discussion with @angelleye  in https://angelleye.atlassian.net/browse/PPCL-5
> we need to turn the "In Context" demo kit into "Smart Buttons" demo kit and use JSv4 integration. Go ahead and get that done in the demo kit GitHub repo please.

**Comment by tejasm-itpath** [comment]
@angelleye 
We need to replace some images in our main index page here 
https://www.screencast.com/t/CLN7YqWg2CCd

I know you sent me this PSD file before but I lost it :(
And if you want to make better design or image then I will take help from our designer.

**Comment by angelleye** [comment]
@tejasm-itpath We don't need a separate demo kit for everything they're showing.  We just need a single demo kit for Smart Buttons, and then inside the comments of that demo kit (and in the display front end) we can add notes/tips about how to customize the Smart Buttons based on PayPal's samples.

**Comment by angelleye** [comment]
@tejasm-itpath 
[home-page-thumbnails.zip](https://github.com/angelleye/paypal-php-library-demo/files/2416110/home-page-thumbnails.zip)

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PCLDK-4
