### ISSUE TITLE
Samples - Express Checkout - Parallel Payments

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library-demo#6]
Moved from https://github.com/angelleye/paypal-php-library/issues/43

**Comment by angelleye** [comment]
You'll notice in the SetExpressCheckout and DoExpressCheckoutPayment files there is a $Payments array with an individual $Payment array inside of it.  This is because PayPal Express supports a split (parallel) payment where multiple payments can be included and sent to multiple sellers in a single checkout.

That's what we need to demo here.  What I'd like to do is setup the cart demo with 2 items like usual, but then have one item's payment sent to one seller account, and the other item's payment sent to a different seller account.

Just like in #7 we'll use the selleraccountid parameter to get this done, but the $Payments array will simply get two $Payment arrays added to it.

**Comment by angelleye** [comment]
The graphic is the one for PayFlow Recurring Billing.  Need to get that updated to say "Express Parallel" similar to the other Express demos.

**Comment by angelleye** [comment]
Looks like we have a $Payment array commented out in the SetExpressCheckout.php file.  The point of these demos is to be clean and easy to follow.  Need to get rid of left over stuff that isn't getting used.

**Comment by angelleye** [comment]
When an API error happens you're just dumping out the errors instead of redirecting to the error page (which is commented out).  Need to clean this up and make it redirect like the other demos.  Again, need this all to be nice and clean and follow the same flow as the others as much as possible.

**Comment by angelleye** [comment]
The review page after being returned from PayPal has a section for the Shipping address, but it seems there is no shipping address coming back so we just end up with a bunch of empty space (except for a comma that was left over)...

![image](https://cloud.githubusercontent.com/assets/629241/15308420/9a295adc-1ba2-11e6-8455-751c96c983e9.png)

Again, this sort of thing needs to be cleaned up.  The code should be checking whether or not shipping details were included in the response, and if not, don't show that area.  

Seems we should be getting shipping details at this point, though, so we need to figure out why they're coming up blank..??

**Comment by angelleye** [comment]
With a parallel payment there are 2 transactions taking place.  As such, we actually get two separate sets of transaction details back in the API response, which means we'll have two separate transaction IDs.

On the completed page, though, you're only outputting a single transaction ID.  

The API response looks like this:

```
Array
(
    [TOKEN] => EC-7U681830B7652245H
    [SUCCESSPAGEREDIRECTREQUESTED] => false
    [TIMESTAMP] => 2016-05-17T01:12:15Z
    [CORRELATIONID] => 510159e6669b
    [ACK] => Success
    [VERSION] => 119.0
    [BUILD] => 22120179
    [INSURANCEOPTIONSELECTED] => false
    [SHIPPINGOPTIONISDEFAULT] => false
    [PAYMENTINFO_0_TRANSACTIONID] => 7H243948GD2589537
    [PAYMENTINFO_0_TRANSACTIONTYPE] => expresscheckout
    [PAYMENTINFO_0_PAYMENTTYPE] => instant
    [PAYMENTINFO_0_ORDERTIME] => 2016-05-17T01:12:10Z
    [PAYMENTINFO_0_AMT] => 19.98
    [PAYMENTINFO_0_FEEAMT] => 0.88
    [PAYMENTINFO_0_TAXAMT] => 0.00
    [PAYMENTINFO_0_CURRENCYCODE] => USD
    [PAYMENTINFO_0_PAYMENTSTATUS] => Pending
    [PAYMENTINFO_0_PENDINGREASON] => paymentreview
    [PAYMENTINFO_0_REASONCODE] => None
    [PAYMENTINFO_0_PROTECTIONELIGIBILITY] => Ineligible
    [PAYMENTINFO_0_PROTECTIONELIGIBILITYTYPE] => None
    [PAYMENTINFO_0_SELLERPAYPALACCOUNTID] => vivekp@itpathsolutions.co.in
    [PAYMENTINFO_0_SECUREMERCHANTACCOUNTID] => E4V8LV8HSZHBJ
    [PAYMENTINFO_0_PAYMENTREQUESTID] => CART26488-PAYMENT0
    [PAYMENTINFO_0_ERRORCODE] => 0
    [PAYMENTINFO_0_ACK] => Success
    [PAYMENTINFO_1_TRANSACTIONID] => 68730492FY7040808
    [PAYMENTINFO_1_TRANSACTIONTYPE] => expresscheckout
    [PAYMENTINFO_1_PAYMENTTYPE] => instant
    [PAYMENTINFO_1_ORDERTIME] => 2016-05-17T01:12:13Z
    [PAYMENTINFO_1_AMT] => 4.99
    [PAYMENTINFO_1_FEEAMT] => 0.44
    [PAYMENTINFO_1_TAXAMT] => 0.00
    [PAYMENTINFO_1_CURRENCYCODE] => USD
    [PAYMENTINFO_1_PAYMENTSTATUS] => Pending
    [PAYMENTINFO_1_PENDINGREASON] => paymentreview
    [PAYMENTINFO_1_REASONCODE] => None
    [PAYMENTINFO_1_PROTECTIONELIGIBILITY] => Ineligible
    [PAYMENTINFO_1_PROTECTIONELIGIBILITYTYPE] => None
    [PAYMENTINFO_1_SELLERPAYPALACCOUNTID] => vivekp@itpathsolutions.co.in
    [PAYMENTINFO_1_SECUREMERCHANTACCOUNTID] => E4V8LV8HSZHBJ
    [PAYMENTINFO_1_PAYMENTREQUESTID] => CART26488-PAYMENT1
    [PAYMENTINFO_1_ERRORCODE] => 0
    [PAYMENTINFO_1_ACK] => Success
)
```

So you can see that it has PAYMENTINFO_0 and PAYMENTINFO_1 which represent the two different transactions and their data.  

The class library includes a GetPayments() method that can be used to parse this out into a $Payments array which you can then loop through to pull out details for each individual payment.

This actually needs to be done even with a single payment, which is probably why the shipping info is getting left blank.

Take a look at /demo/express-checkout-line-items/GetExpressCheckoutDetails.php for an example of using the GetPayments() method to parse the payments in the response into an array, and then you'll see how it's setting the shipping address there as well.  

Again, this needs to be done to clean up our results and provide all the necessary data for both transactions on the order.

**Comment by angelleye** [comment]
It seems that you've made some adjustments to the .gitignore file in this branch for some reason.  I see you added a logs folder and some composer files, and you removed the config.php file from ignore..??  That is not correct.  We'll need to discuss the proper way to manage config files in projects like this.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PCLDK-11
