### ISSUE TITLE
Samples - Express Checkout - 3rd Party No Permissions Required

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library-demo#7]
Moved from https://github.com/angelleye/paypal-php-library/issues/44

**Comment by angelleye** [comment]
This is essentially the exact same thing as #1 except that we'll add the $Payment['sellerpaypalaccountid'] parameter to the SetExpressCheckout and DoExpressCheckoutPayment request files to specify that the payment should go to a 3rd party.

So we'll use the same credentials we always use as a test seller account, but then we'll use the email address of a separate sandbox seller account where the money will fall.

**Comment by keyurptl** [comment]
I am done with #7, Please review it.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PCLDK-2
