### ISSUE TITLE
Samples - Express Checkout - Redeemed Offers

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-php-library-demo#8]
Moved from https://github.com/angelleye/paypal-php-library/issues/46

**Comment by angelleye** [comment]
Here is a link to documentation that covers this procedure:  https://developer.paypal.com/docs/classic/express-checkout/ht_ec-coupons-loyalty-programs/

**Comment by keyurptl** [comment]
This is done in paypal-php-library Issue-80

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PCLDK-3
